### PR TITLE
27 range voting wizard

### PR DESCRIPTION
**Pull request by rkzel**
Updates from master have been merged into the branch, no major conflicts.

This is the most current UI work.

### CODE REVIEW

**Comment by Quazia** [comment]
Travis checks need to pass before we merge this in. I can try and see what's failing; chances are merging downstream will solve this.

**Comment by rkzel** [comment]
One module went AWOL, ethereumjs-abi - I added it back and local testing is now happy.

**Comment by Quazia** [comment]
LGTM, there are some holes obviously but the priority is to get this merged in quick for the time being. If possible could you reference the issue number of all issues that are cleared in this PR?

**Comment by Quazia** [comment]
I'm just going to merge this in but it'd still be useful to link any issues this is supposed to clear.

**Pull request merged**
